/*
 * HTGL ESP32 + ST7789 port
 *
 * Drives a 240x240 ST7789 panel via TFT_eSPI.
 * The embedded UI is compiled from port/esp32/ui.html via:
 *   python ../../tool/htgl.py ui.html -o /tmp/ui.uib --emit-c src/ui_blob.c --symbol ui
 *
 * Pin configuration is in platformio.ini — edit the -DTFT_* build_flags
 * to match your wiring before flashing.
 */

#include <Arduino.h>
#include <TFT_eSPI.h>

// HTGL engine headers — extern "C" guards are already in the headers,
// but we wrap explicitly here for clarity.
extern "C" {
#include "htgl.h"
#include "htgl_internal.h"
}

// Embedded UI blob (generated by the transpiler, lives in ui_blob.c)
extern "C" {
    extern const unsigned char  ui_blob[];
    extern const unsigned int   ui_blob_len;
}

// ── Display ──────────────────────────────────────────────────────────────────

static TFT_eSPI tft;

// Band render buffer: 240 px wide × 16 rows = 3840 RGB565 words (~7.5 KB DRAM)
static uint16_t line_buf[240 * 16];

// ── HTGL context (stack-allocated via htgl_internal.h struct) ────────────────

static htgl_ctx ctx;

// ── HAL callback ─────────────────────────────────────────────────────────────

// Called by htgl_render() for each rendered band.
// setSwapBytes(true) makes TFT_eSPI byte-swap our little-endian RGB565 values
// so the panel receives them in the big-endian order ST7789 expects.
static void flush(int x, int y, int w, int h, const uint16_t *buf) {
    tft.setSwapBytes(true);
    tft.pushImage(x, y, w, h, (uint16_t *)buf);
}

// ── Tap handler ──────────────────────────────────────────────────────────────

// Called when the user taps a data-tap element.
// Note: tap input requires a touch controller (most bare ST7789 boards have
// none).  Wire htgl_pointer_down / htgl_pointer_up to your touch IC ISR to
// enable tap events.  Animation runs regardless.
static void tap_handler(int tap_id, void * /*user*/) {
    Serial.printf("[htgl] tap id=%d\n", tap_id);
}

// ── Arduino entry points ──────────────────────────────────────────────────────

void setup() {
    Serial.begin(115200);
    Serial.println("[htgl] boot");

    // Initialise display
    tft.init();
    tft.setRotation(0);
    tft.fillScreen(TFT_BLACK);

    // Enable backlight (pin and polarity defined in platformio.ini build_flags)
#ifdef TFT_BL
    pinMode(TFT_BL, OUTPUT);
    digitalWrite(TFT_BL, TFT_BL_ON);
#endif

    // Build the HAL
    static const htgl_hal hal = { flush };

    // Initialise HTGL engine
    htgl_init(&ctx, &hal, line_buf, 240 * 16);

    // Load the embedded UI blob
    int rc = htgl_load(&ctx, ui_blob, (int)ui_blob_len);
    if (rc != 0) {
        Serial.printf("[htgl] htgl_load failed: %d\n", rc);
        // Halt — bad blob
        while (true) { delay(1000); }
    }

    // Register tap callback
    htgl_set_tap_handler(&ctx, tap_handler, nullptr);

    Serial.printf("[htgl] loaded %u bytes, screen %dx%d\n",
                  ui_blob_len,
                  htgl_screen_w(&ctx),
                  htgl_screen_h(&ctx));
}

void loop() {
    // Advance animation clock
    htgl_tick(&ctx, (uint32_t)millis());

    // Resolve layout (animations move nodes, so call every frame)
    htgl_layout(&ctx);

    // Render the full screen in 16-row bands, flushed via TFT_eSPI
    htgl_render(&ctx);

    // ~60 fps cap; omit or reduce if you want max throughput
    delay(16);
}
