"""`.uib` bytes -> C source array (compile-time embedding mode)."""


def emit_c_array(blob, symbol):
    lines = [
        "/* Auto-generated by htgl. Do not edit. */",
        f"const unsigned char {symbol}_blob[] = {{",
    ]
    row = []
    for b in blob:
        row.append(f"0x{b:02x},")
        if len(row) == 12:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("};")
    lines.append(f"const unsigned int {symbol}_blob_len = {len(blob)};")
    lines.append("")
    return "\n".join(lines)
